import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css'
import { Inter } from 'next/font/google';
import Footer from './components/footer/page';
import Header from './components/header/page';
import MyLayout from './components/layout/page';
import '../style.css'
import Sidebar from './components/sidebar/page';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'NWG E-Commerce',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-pzjw8f+ua8z5Fk1I3j5f5P7KwF5W5v5W5z5W5v5W5z5W5v5W5z5W5v5W5v5W5v5W5v5"
          crossOrigin="anonymous"
        />
        <script
          src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossOrigin="anonymous"
        ></script>
        <script
          src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
          integrity="sha384-pzjw8f+ua8z5Fk1I3j5f5P7KwF5W5v5W5z5W5v5W5z5W5v5W5z5W5v5W5v5W5v5W5v5"
          crossOrigin="anonymous"
        ></script>

        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q1"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <body className={inter.className}>
        <div id='page_size'>
          
          <MyLayout>
            {children}
          </MyLayout>
         
          


        </div>

      </body>
    </html>
  );
}
